In [14]:
import numpy as np
from random import *
import decimal

class Movie:
    def __init__(self, title="",year=0,runtime=0):
        self.title = title
        self.year = year
        if runtime < 0:
            self.runtime = 0
        else:
            self.runtime = runtime
        
    def __repr__(self):
        return self.title + " (" + str(self.year) + ") - " + str(self.runtime) + " mins."
    
    
    def getRunTime(self):
        h = self.runtime / 60
        m = self.runtime 
        return h,m

In [28]:
m = Movie("Jurassic World", 2015, 124)

In [29]:
print(m)

Jurassic World (2015) - 124 mins.


In [30]:
m.getRunTime()

(2, 124)

In [42]:
def create_movie_list():
    myList = []
    m1 = Movie("Avatar", 2012, 140)
    m2 = Movie("Pokemon", 2017, 160)
    m3 = Movie("Star Wars", 2017, 180)
    m4 = Movie("2012",2008,100)
    myList.append(m)
    myList.append(m1)
    myList.append(m2)
    myList.append(m3)
    myList.append(m4)
    return myList

In [69]:
def main():
    movieList = create_movie_list()
    myDict = {}
    newList = [i  for i in movieList if i.getRunTime()[1] > 150]
    print("***************")
  
    for i in movieList:
        myDict[i] = float(random.randrange(0, 500))/100
  
    for i,x in myDict.iteritems():
        print i, x
    
        
    

In [70]:
main()

***************
2012 (2008) - 100 mins. 2.28
Jurassic World (2015) - 124 mins. 1.85
Avatar (2012) - 140 mins. 3.73
Pokemon (2017) - 160 mins. 3.36
Star Wars (2017) - 180 mins. 4.03


In [11]:
def get_movie_data():
    """
    Generate a numpy array of movie data
    :return:
    """
    num_movies = 10
    array = np.zeros([num_movies, 3], dtype=np.float)

    random = Random()

    for i in range(num_movies):
        # There is nothing magic about 100 here, just didn't want ids
        # to match the row numbers
        movie_id = i + 100
        
        # Lets have the views range from 100-10000
        views = random.randint(100, 10000)
        stars = random.uniform(0, 5)

        array[i][0] = movie_id
        array[i][1] = views
        array[i][2] = stars

    return array

In [54]:
def main():
    myArray = get_movie_data()
    print myArray
    #print 'Num rols: ' + str(np.shape(myArray)[0])
    #print 'Num cols: ' + str(np.shape(myArray)[1])
    #print(myArray[:3])
    print '*********'
    #print myArray[:,[1,2]]
    print myArray[:,1]

In [55]:
main()

[[  1.00000000e+02   2.87900000e+03   1.86378211e+00]
 [  1.01000000e+02   4.76700000e+03   3.26562927e+00]
 [  1.02000000e+02   7.86200000e+03   3.93567769e+00]
 [  1.03000000e+02   6.89300000e+03   4.39453149e+00]
 [  1.04000000e+02   6.44000000e+03   2.89409057e+00]
 [  1.05000000e+02   1.07800000e+03   2.90964525e-01]
 [  1.06000000e+02   3.00000000e+03   3.36877339e+00]
 [  1.07000000e+02   6.77500000e+03   2.46961900e+00]
 [  1.08000000e+02   3.36200000e+03   1.84876467e+00]
 [  1.09000000e+02   6.91800000e+03   2.10740103e+00]]
*********
[ 2879.  4767.  7862.  6893.  6440.  1078.  3000.  6775.  3362.  6918.]
